# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8819fac8a0304b144a790a1a7970cbe687da2df778b0ccded60366eb52582b76460e1559c0e0f1c6f9bf2426497d28520e4c841c892a697f2dd0fe37c01e4fdb

test:
  secret_key_base: e205d1b3ac5e1c4d09c35033401d0a59ba2f2765d43dacf262b0b3e53cd1ab07a14d8acf23976133de8aa804c9bc7a7c01bd0c1726da62150a6e6643abbfad66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
